[project]
name = "anti-rocky"
version = "0.1.0"
description = "Saving earth from asteroids since 2025-10-04 09:00 CEST"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]

[dependency-groups]
dev = [
  "pytest"
]
lint = [
  "ruff"
]
