name: CI/CD Pipeline

on:
  push:
    branches: ["*"]
  pull_request:

jobs:
  lint:
    name: ✨ Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install project dependencies
        run: uv sync

      - name: Run Ruff Linting
        run: uvx ruff check --output-format=github

  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    env:
      TERRAFORM_DIR: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install
        run: uv sync

      - id: 'auth'
        name: Authenticate with Google Cloud Platform
        uses: 'google-github-actions/auth@v3'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Install gcloud CLI
        uses: google-github-actions/setup-gcloud@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ${{ env.TERRAFORM_DIR }}
        run: terraform init

      - name: Terraform Apply
        working-directory: ${{ env.TERRAFORM_DIR }}
        run: terraform apply -auto-approve -lock-timeout=5m
