name: CI/CD Pipeline

on:
  push:
    branches: ["*"]
  pull_request:

jobs:
  lint:
    name: ✨ Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install project dependencies
        run: uv sync

      - name: Run Ruff Linting
        run: uvx ruff check --output-format=github

  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    env:
      TERRAFORM_DIR: terraform

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install
        run: uv sync

      - id: 'auth'
        name: Authenticate with Google Cloud Platform
        uses: 'google-github-actions/auth@v3'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Install gcloud CLI
        uses: google-github-actions/setup-gcloud@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ${{ env.TERRAFORM_DIR }}
        run: terraform init

      - name: Terraform Apply
        working-directory: ${{ env.TERRAFORM_DIR }}
        run: terraform apply -input=false -auto-approve -lock-timeout=5m

      - name: Authenticate Docker Cloud
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Build and push API
        run: |
          docker build -t europe-west1-docker.pkg.dev/anti-rocky/anti-rocky/api:latest api
          docker push europe-west1-docker.pkg.dev/anti-rocky/anti-rocky/api:latest
          gcloud run services update api \
            --image europe-west1-docker.pkg.dev/anti-rocky/anti-rocky/api:latest \
            --region europe-west1 \
            --set-env-vars neo_api_key=${{ secrets.NEO_API_KEY }},env=production
